backend:
  name: github
  branch: main # change this to your branch
  repo: garrison0/clc # change this to your repo
  site_domain: melodic-brioche-682b75.netlify.app # change this to your domain
  base_url: https://melodic-brioche-682b75.netlify.app/ # change this to your prod URL
  auth_endpoint: oauth

site_url: https://melodic-brioche-682b75.netlify.app/

publish_mode: editorial_workflow
media_folder: "assets/uploads"

collections:
  - name: 'pages'
    label: 'Pages'
    folder: "_pages"
    delete: false # Prevent users from deleting documents in this collection
    files:
      - name: 'homepage'
        label: 'Homepage'
        file: 'site/content/homepage.yml'
        # service times, list of announcements
        description: 'Homepage data'
        fields:
          - label: 'Service times'
            name: 'service-times'
            widget: 'string' 
          - label: 'Announcements'
            name: 'announcements'
            widget: list
            fields:
              - {
                  label: 'Announcement date',
                  name: "datetime",
                  widget: "datetime"
                }
              - { label: 'Announcement',
                  name: 'announcement',
                  widget: 'string'
                ]