backend:
  name: github
  branch: main # change this to your branch
  repo: garrison0/clc # change this to your repo
  site_domain: melodic-brioche-682b75.netlify.app # change this to your domain
  base_url: https://melodic-brioche-682b75.netlify.app/ # change this to your prod URL
  auth_endpoint: oauth

site_url: https://melodic-brioche-682b75.netlify.app/

publish_mode: editorial_workflow
media_folder: "/uploads/"
public_folder: ""

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "src/data/settings.json" # Or .yml, .md, etc.
        label: "Global Settings"
        name: "global_settings"
        fields:
          - label: "Giving link"
            name: "givingLink"
            widget: "string"
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    delete: false # Prevent users from deleting documents in this collection
    files:
      - name: 'homepage'
        label: 'Homepage'
        file: 'site/content/homepage.yml'
        description: 'Homepage data'
        fields:
          - label: 'Mission statement'
            name: 'missionStatement'
            widget: 'text'
          - label: 'Service times'
            name: 'serviceTimes'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Day of week', 
                  name: "day", 
                  widget: select,
                  options: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
                } 
              - { label: "Start time",
                  name: "start",
                  widget: "string"
                }
          - label: 'Announcements'
            name: 'announcements'
            widget: list
            fields:
              - { label: 'Announcement title',
                  name: 'title',
                  widget: 'string'
                }
              - {
                  label: 'Announcement date',
                  name: "datetime",
                  widget: "datetime"
                }
              - { label: 'Announcement description',
                  name: 'description',
                  widget: 'string'
                }
      - name: 'about'
        label: 'About page'
        file: 'site/content/about.yml'
        description: 'About page data'
        fields:
          - {label: "What we believe", name: "beliefs", widget: "text"}
          - { label: "Pastoral care description", name: "pastoralCareDescription", widget: "text" }
          - label: 'Pastoral care information'
            name: 'pastoralCare'
            widget: 'list'
            fields:
            - { label: "Type of care", name: "typeOfCare", widget: "string" }
            - { label: "Description of care", name: "description", widget: "text" }
      - name: 'Contact'
        label: 'Contact page'
        file: 'site/content/contact.yml'
        description: 'Contact page data'
        fields:
          - { label: 'Address', name: 'address', widget: 'string' }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone number", name: "phone", widget: "string" }
          - { label: "Fax", name: "fax", widget: "string", required: false }
          - label: 'Staff information'
            name: 'staffInformation'
            widget: 'list'
            fields:
              - { label: 'Work title', name: 'title', widget: 'string' }
              - { label: "name", name: "name", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
              - { label: "Phone number", name: "phone", widget: "string", required: false }
              - { label: 'Description', name: 'description', widget: 'text', required: false }
              - label: "Headshot"
                name: "headshot"
                widget: "image"
                choose_url: true
                required: false
      - name: 'Ministries'
        label: 'Ministries page'
        file: 'site/content/ministries.yml'
        description: 'Ministries page data'
        fields:
          - label: "Ministries"
            name: 'ministries'
            widget: 'list'
            fields:
            - { label: 'Title of ministry', name: 'title', widget: 'string' }
            - { label: "Description of ministry", name: "description", widget: "text" }
            - { label: "Ministry picture", name: "image", widget: "image", required: false }
            - label: 'Calls to action'
              name: 'callsToAction'
              widget: 'list'
              fields:
              - { label: "Header", name: "header", widget: "string", required: false }
              - { label: "Description", name: "description", widget: "text", required: false }
              - { label: 'Call to action', 
                  required: false,
                  name: "call", 
                  widget: select,
                  options: ["Contact the church office", "Contact our pastor"]
                } 
