backend:
  name: github
  branch: main # change this to your branch
  repo: garrison0/clc # change this to your repo
  site_domain: melodic-brioche-682b75.netlify.app # change this to your domain
  base_url: https://melodic-brioche-682b75.netlify.app/ # change this to your prod URL
  auth_endpoint: oauth # the oauth route provided by the integration

site_url: https://example.com

publish_mode: editorial_workflow
media_folder: assets/uploads

collections:
  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Settings'
        file: '_data/settings.json'
        description: 'General Site Settings'
        fields:
          - { label: 'Global title', name: 'site_title', widget: 'string' }
          - label: 'Post Settings'
            name: posts
            widget: 'object'
            fields:
              - {
                  label: 'Number of posts on frontpage',
                  name: front_limit,
                  widget: number,
                  min: 1,
                  max: 10,
                }
              - { label: 'Default Author', name: author, widget: string }
              - {
                  label: 'Default Thumbnail',
                  name: thumb,
                  widget: image,
                  class: 'thumb',
                  required: false,
                }